### ISSUE TITLE
imagesize library not supported 'bmp' image

### ISSUE THREAD

**Issue by kkt8282** [Taeyoung96/Yolo-to-COCO-format-converter#15]
First of all, thank you for providing a great source code!!

I'm using an image with 'bmp' extension.

The latest version uses the imagesize library.

But libraries do not support extensions.

Why are you using 'imagesize' instead of 'imread -> img.shape'??

**Comment by Taeyoung96** [comment]
Hi,  @kkt8282   

I merged PR #12 because of the image loading speed.  

If you want to use `imread` function, you just fixed some codes referring to [this](https://github.com/Taeyoung96/Yolo-to-COCO-format-converter/pull/12/files#).  

Maybe, when you use `bmp` extenstion, you add some codes like [this](https://github.com/Taeyoung96/Yolo-to-COCO-format-converter/pull/14/files).  

Thanks,
